### ISSUE TITLE
Scalar: default rust-theme font

### ISSUE THREAD

**Issue by pchrszon-dlr** [tamasfe/aide#226]
In `crates/aide/res/scalar/rust-theme.css`, the Scalar font is defined as:

```css
:root {
  --scalar-font: "Inter", var(--system-fonts);
}
```

Both Firefox and Edge report that the variable `--system-fonts` is not defined. Thus, if the `Inter` font is not installed, the browser applies its default font (which is serif/Times New Roman on my machine). In case this is not intended, I think adding `sans-serif` to the rule would provide a better fallback, since `Inter` is also a sans-serif font.
