### ISSUE TITLE
How to require multiple securitySchemas?

### ISSUE THREAD

**Issue by nappa85** [tamasfe/aide#25]
https://swagger.io/docs/specification/authentication/api-keys/
As of specification, you can define multiple apiKeys to work in a group.

I'm looking for a way to specify the same with aide, but I can't find it.

Let's say I have 2 apiKeys, like:
```yaml
components:
  securitySchemes:
    bar1:
      type: apiKey
      in: header
      name: X-BAR1
    bar2:
      type: apiKey
      in: header
      name: X-BAR2
```

`OpenApi::security` field is a `Vec<IndexMap<String, Vec<String>>>` and setting it like
```rust
OpenApi {
  components: Some(Components {
    security_schemes: [
      ("bar1".to_string(), ReferenceOr::Item(SecurityScheme::ApiKey {
        name: "X-BAR1".to_string(),
        location: ApiKeyLocation::Header,
        description: None,
        extensions: [].into(),
      })), ("bar2".to_string(), ReferenceOr::Item(SecurityScheme::ApiKey {
        name: "X-BAR2".to_string(),
        location: ApiKeyLocation::Header,
        description: None,
        extensions: [].into(),
      }))
    ].into(),
    ..openapi::Components::default()
  }),
  security: vec![[("foo".to_owned(), vec!["bar1".to_owned(), "bar2".to_owned()])].into()],
  ..OpenApi::default()
}
```

produces
```yaml
components:
  securitySchemes:
    bar1:
      type: apiKey
      in: header
      name: X-BAR1
    bar2:
      type: apiKey
      in: header
      name: X-BAR2
security:
- foo:
  - bar1
  - bar2
```

that it's not what I want.

`TransformOperation::security_requirement` accepts only an `&str`, passing "foo" from previous example, inside the method, produces
```yaml
      security:
      - foo: []
```

but redocs doesn't recognizes it.

`TransformOperation::security_requirement_scopes` accepts a `&str` and anything that can be used as an Iterator of String, passing "foo" and `["bar1", "bar2"]` from previous example, inside the method, produces
```yaml
      security:
      - foo:
        - bar1
        - bar2
```

What's the correct approach here? Is it a crate limitation?
