### ISSUE TITLE
Docs examples for aide::axum do not compile

### ISSUE THREAD

**Issue by sminez** [tamasfe/aide#3]
It looks like the minimal example given [here](https://docs.rs/aide/latest/aide/axum/index.html#examples) does not compile due to `Json` not implementing `OperationOutput` / `OperationInput`. Is there a minimal example to refer to other than the one in https://github.com/tamasfe/aide/tree/master/examples/example-axum ? That seems to be implementing a custom `Json` extractor so I'm guessing that would need to be done for the other build in extractors from axum such as `Query`?

I'm really interested in making use of `aide` but it's looking like I need to provide new type wrappers for ever axum extractor I want to make use of which is surprising...

Hopefully I'm just misunderstanding something 😅

**Comment by tamasfe** [comment]
Thanks. The doctest indeed fails but it's due to `OpenApi` not implementing `JsonSchema`.

Do you have the `axum` feature enabled?

**Comment by sminez** [comment]
Sorry, just re-running things now and seeing that that indeed is the issue!
```
error[E0277]: the trait bound `OpenApi: JsonSchema` is not satisfied
  --> src/main.rs:27:80
   |
27 |   async fn serve_api(Extension(api): Extension<OpenApi>) -> impl IntoApiResponse {
   |  ________________________________________________________________________________-
28 | |     Json(api)
29 | | }
   | | ^
   | | |
   | |_the trait `JsonSchema` is not implemented for `OpenApi`
   |   required by a bound introduced by this call
   |
   = help: the following other types implement trait `JsonSchema`:
             &'a T
             &'a mut T
             ()
             (T0, T1)
             (T0, T1, T2)
             (T0, T1, T2, T3)
             (T0, T1, T2, T3, T4)
             (T0, T1, T2, T3, T4, T5)
           and 132 others
   = note: required because of the requirements on the impl of `OperationOutput` for `Json<OpenApi>`
   = note: required because of the requirements on the impl of `IntoApiResponse` for `Json<OpenApi>`
```

The Cargo.toml I have is based on the one from `example-axum`:
```toml
[package]
name = "openapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aide = { version = "0.6.0", features = ["axum", "axum-extra", "macros"] }
async-trait = "0.1.57"
axum = { version = "0.6.0-rc.1", features = ["macros"] }
axum-extra = "0.4.0-rc.1"
axum-macros = "0.3.0-rc.1"
schemars = { version = "0.8.10", features = ["uuid1"] }
serde = { version = "1.0.144", features = ["derive", "rc"] }
serde_json = "1.0.85"
tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread"] }
```
